import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { UserCheck, Check } from "lucide-react";
import { api, type Member, type Package } from "@/lib/store";

export default function AddMember() {
  const navigate = useNavigate();
  const [packages, setPackages] = useState<Package[]>([]);

  useEffect(() => {
    api.getPackages().then(setPackages).catch(console.error);
  }, []);

  const [form, setForm] = useState({
    name: "",
    email: "",
    phone: "",
    gender: "Male",
    dateOfJoining: new Date().toISOString().split("T")[0],
    packageId: "",
    customPlan: false,
    customPrice: "",
    customDuration: "",
  });

  // Set default package when packages are loaded
  useEffect(() => {
    if (packages.length > 0 && !form.packageId) {
      setForm(prev => ({ ...prev, packageId: packages[0].id || packages[0]._id || "" }));
    }
  }, [packages]);

  const [saved, setSaved] = useState(false);

  const update = (key: string, value: string | boolean) =>
    setForm((prev) => ({ ...prev, [key]: value }));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.name.trim() || !form.phone.trim()) return;

    const pkg = packages.find((p) => (p.id || p._id) === form.packageId);
    const price = form.customPlan ? Number(form.customPrice) : pkg?.price || 0;
    const duration = form.customPlan ? Number(form.customDuration) : pkg?.duration || 30;

    const joinDate = new Date(form.dateOfJoining);
    const expiryDate = new Date(joinDate.getTime() + duration * 86400000)
      .toISOString()
      .split("T")[0];

    // Note: ID is generated by backend usually, but for transaction linking we might need it.
    // Or we let backend return it.

    try {
      const newMemberData = {
        name: form.name.trim(),
        email: form.email.trim(),
        phone: form.phone.trim(),
        gender: form.gender,
        dateOfJoining: form.dateOfJoining,
        packageId: form.customPlan ? undefined : form.packageId,
        customPlan: form.customPlan,
        customPrice: form.customPlan ? Number(form.customPrice) : undefined,
        customDuration: form.customPlan ? Number(form.customDuration) : undefined,
        amountPaid: 0,
        expiryDate,
      };

      const savedMember = await api.addMember(newMemberData);

      // Auto-create transaction
      await api.addTransaction({
        memberId: savedMember._id || savedMember.id,
        memberName: savedMember.name,
        packageName: form.customPlan ? `Custom Plan` : pkg?.name || "N/A",
        totalPrice: price,
        amountPaid: 0,
        dueAmount: price,
        date: form.dateOfJoining,
      });

      setSaved(true);
      setTimeout(() => navigate("/members"), 1200);
    } catch (error) {
      console.error("Failed to add member", error);
      alert("Failed to add member. Please try again.");
    }
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-foreground">Add New Member</h2>
        <p className="text-muted-foreground text-sm mt-1">Register a new gym member</p>
      </div>

      {saved ? (
        <div className="glass-card p-8 md:p-12 text-center space-y-4">
          <div className="w-16 h-16 bg-success/10 text-success rounded-full flex items-center justify-center mx-auto mb-4">
            <Check size={32} className="text-success" />
          </div>
          <p className="text-lg font-semibold text-foreground">Member Added Successfully!</p>
          <p className="text-sm text-muted-foreground">Redirecting to members list...</p>
        </div>
      ) : (
        <form onSubmit={handleSubmit} className="glass-card p-4 md:p-6 space-y-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">Name *</label>
              <input
                required
                value={form.name}
                onChange={(e) => update("name", e.target.value)}
                className="w-full px-4 py-2.5 rounded-lg bg-secondary border border-border text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                placeholder="Full name"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">Email</label>
              <input
                type="email"
                value={form.email}
                onChange={(e) => update("email", e.target.value)}
                className="w-full px-4 py-2.5 rounded-lg bg-secondary border border-border text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                placeholder="email@example.com"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">Phone *</label>
              <input
                required
                value={form.phone}
                onChange={(e) => update("phone", e.target.value)}
                className="w-full px-4 py-2.5 rounded-lg bg-secondary border border-border text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                placeholder="9876543210"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">Gender</label>
              <select
                value={form.gender}
                onChange={(e) => update("gender", e.target.value)}
                className="w-full px-4 py-2.5 rounded-lg bg-secondary border border-border text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
              >
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
              </select>
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">Date of Joining</label>
              <input
                type="date"
                value={form.dateOfJoining}
                onChange={(e) => update("dateOfJoining", e.target.value)}
                className="w-full px-4 py-2.5 rounded-lg bg-secondary border border-border text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
              />
            </div>
          </div>

          {/* Custom Plan Toggle */}
          <div className="flex items-center gap-3 pt-2">
            <button
              type="button"
              onClick={() => update("customPlan", !form.customPlan)}
              className={`relative w-10 h-5 rounded-full transition-colors ${form.customPlan ? "bg-primary" : "bg-border"
                }`}
            >
              <span
                className={`absolute top-0.5 left-0.5 w-4 h-4 rounded-full bg-foreground transition-transform ${form.customPlan ? "translate-x-5" : ""
                  }`}
              />
            </button>
            <label className="text-sm font-medium text-foreground">Custom Plan</label>
          </div>

          {form.customPlan ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground">Custom Price (₹)</label>
                <input
                  type="number"
                  required
                  value={form.customPrice}
                  onChange={(e) => update("customPrice", e.target.value)}
                  className="w-full px-4 py-2.5 rounded-lg bg-secondary border border-border text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="2500"
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground">Duration (days)</label>
                <input
                  type="number"
                  required
                  value={form.customDuration}
                  onChange={(e) => update("customDuration", e.target.value)}
                  className="w-full px-4 py-2.5 rounded-lg bg-secondary border border-border text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="45"
                />
              </div>
            </div>
          ) : (
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">Select Package</label>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                {packages.map((pkg) => {
                  const pkgId = pkg.id || pkg._id || "";
                  return (
                    <button
                      type="button"
                      key={pkgId}
                      onClick={() => update("packageId", pkgId)}
                      className={`p-4 rounded-xl border text-left transition-all ${form.packageId === pkgId
                        ? "border-primary bg-primary/10 glow-blue"
                        : "border-border bg-secondary hover:border-primary/30"
                        }`}
                    >
                      <p className="font-semibold text-foreground text-sm">{pkg.name}</p>
                      <p className="text-primary font-bold mt-1">₹{pkg.price.toLocaleString()}</p>
                      <p className="text-xs text-muted-foreground mt-1">{pkg.duration} days</p>
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          <button
            type="submit"
            className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-lg bg-primary text-primary-foreground font-medium hover:bg-primary/90 glow-blue transition-all"
          >
            <UserCheck size={18} />
            Register Member
          </button>
        </form>
      )}
    </div>
  );
}
